version: '3.7'

services:
  web:
    build: ./gloth
    command: python run.py
    volumes:
      - ./gloth/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./gloth.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=gloth
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres

volumes:
  postgres_data: